server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/db_activiti?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    tomcat:
      validation-query: SELECT 1 FROM DUAL
  activiti:
    # #校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: true
    # asyncExecutorActivate是指示activiti在流程引擎启动就激活AsyncExecutor,异步
    async-executor-activate: true
    # 数据源指定
#    database-schema:
    # 使用自定义mybatis-mapper
#     custom-mybatis-mappers: com.asarao.mapper.*
#     custom-mybatis-xmlmappers: classpath:mapper/*Mapper.xml
    # 建表规则
    # flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。
    # true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
    # create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。
    # drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
#     database-schema-update: false
    # 检测历史表是否存在
#    db-history-used: false
    # 检测身份信息表是否存在
#    db-identity-used: false
    # 流程部署名称
#    deployment-name:
    # 记录历史等级 可配置的历史级别有none, acitivity, audit
#    history-level: none
    # spring jpa使用 默认true
    jpa-enabled: false
    # 邮件发送服务配置
#    mail-server-default-from:
#    mail-server-host:
#    mail-server-password:
#    mail-server-port:
#    mail-server-use-ssl:
#    mail-server-use-tls:
#    mail-server-user-name:
    # 自定义流程文件位置
#    processes-definition-location-prefix: classpath:/processes/
#    processes-definition-location-suffixes: '**.bpmn20.xml','**.bpmn'
    # activiti rest 配置
    database-schema-update: true
    process-definition-location-prefix: classpath:/processes/
#    rest-api-enabled: false
#    rest-api-mapping: /api/*
#    rest-api-servlet-name: activitiRestApi


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.asarao.model
  global-config:
    db-config:
      id-type: ID_WORKER
      field-strategy: NOT_EMPTY
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# logging
logging:
  level:
    com.asarao: debug
